portal:
  image: nginx-php-fpm
  ports:
   - "80:80"
  links:
   - payaraOne:payara1
   - payaraTwo:payara2
   - payaraThree:payara3
payaraOne:
  image: docker-payaraserver-full
payaraTwo:
  image: docker-payaraserver-full
payaraThree:
  image: docker-payaraserver-full
