db:
  image: mariadb
  hostname: mariadb
  ports:
    - 3306:3306
redis:
  image: redis
  hostname: redis
  ports: 
    - 6379:6379
portal:
  image: nginx-php-fpm
  ports:
   - "80:80"
  links:
   - payaraOne:payara1
   - payaraTwo:payara2
   - payaraThree:payara3
   - "db: mariadb"
   - redis:redis
payaraOne:
  image: docker-payaraserver-full
  ports:
    - 8080:8080
    - 8443:8443
    - 4848:4848
  volumes:
    - /home/admin/projects/npr-cluster/webapps/test/target/test:/opt/payara41/deployments/ROOT
  links:
    - "db: mariadb"
    - redis:redis
payaraTwo:
  image: docker-payaraserver-full
  ports:
    - 7080:8080
    - 7443:8443
    - 3848:4848
  volumes:
    - /home/admin/projects/npr-cluster/webapps/test/target/test:/opt/payara41/deployments/ROOT
  links:
    - "db: mariadb"
    - redis:redis
payaraThree:
  image: docker-payaraserver-full
  ports:
    - 6080:8080
    - 6443:8443
    - 2848:4848
  volumes:
    - /home/admin/projects/npr-cluster/webapps/test/target/test:/opt/payara41/deployments/ROOT
  links:
    - "db: mariadb"
    - redis:redis
